[package]
name = "vineda"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cgmath = "0.16.1"
gl = "0.14.0"
glfw = {version = "0.39.1", features = ["vulkan"]}
image = "0.19.0"
