[package]
name = "vineda"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytemuck = "1"
ultraviolet = "0.7"
imagine = "0.0.5"
glfw = {version = "0.39.1", features = ["vulkan"]}

